"use client";

import { useState } from "react";
import { money } from "@/lib/format";
import LineChart from "./LineChart";

export default function ScenarioLab({ start, startGdp, cpi }: { start:number; startGdp:number; cpi:number }) {
  const [spend,setSpend]=useState(5),[revenue,setRevenue]=useState(4),[growth,setGrowth]=useState(3.8),[inflation,setInflation]=useState(2.3),[rate,setRate]=useState(4),[years,setYears]=useState(10),[control,setControl]=useState("Neutral / unspecified"),[real,setReal]=useState(false);
  let debt=start,gdp=startGdp,receipts=startGdp*.166,outlays=startGdp*.22;
  const points=[debt];
  for(let i=0;i<years;i++){receipts*=1+revenue/100;outlays*=1+spend/100;const interest=debt*rate/100;debt+=outlays+interest-receipts;gdp*=1+growth/100;points.push(debt)}
  const display=real?points.map((value,index)=>value/Math.pow(1+inflation/100,index)):points;
  const startYear=new Date().getUTCFullYear(),dates=display.map((_,index)=>`${startYear+index}-01-01`);
  const controls:Array<[string,number,(value:number)=>void,number,number]>=[["Spending growth",spend,setSpend,0,10],["Revenue growth",revenue,setRevenue,0,10],["GDP growth",growth,setGrowth,0,8],["Inflation",inflation,setInflation,0,8],["Average interest rate",rate,setRate,0,10],["Forecast horizon",years,setYears,1,20]];
  return <div className="forecastGrid"><div className="panel"><div className="panelHeader chartNarrative"><div><h2>Where do your assumptions take the debt?</h2><p>Each point applies the spending, revenue, growth, inflation, and interest-rate assumptions shown at right.</p></div><span className="pill">Deterministic · user-created</span></div><LineChart intervalControls values={display} dates={dates} labels={display.map((_,index)=>index===0?"Today":`Year ${index}`)} seriesLabel="User scenario" xLabel="Years from latest observation" yLabel={`Total public debt · ${real?"real 2026":"nominal"} USD`}/><div className="grid4"><div className="card"><label>End debt · {real?"real 2026":"nominal"}</label><strong>{money(display.at(-1)!)}</strong></div><div className="card"><label>Debt / GDP</label><strong>{(debt/gdp*100).toFixed(0)}%</strong></div><div className="card"><label>Annual deficit</label><strong>{money(outlays+debt*rate/100-receipts)}</strong></div><div className="card"><label>Horizon</label><strong>{years} yrs</strong></div></div></div><div className="panel controls"><h2>Transparent assumptions</h2><label className="control">Dollar basis <select value={real?"real":"nominal"} onChange={event=>setReal(event.target.value==="real")}><option value="nominal">Nominal</option><option value="real">Real (2026 dollars)</option></select></label><label className="control">Political configuration <select value={control} onChange={event=>setControl(event.target.value)}><option>Neutral / unspecified</option><option>Unified government</option><option>Divided government</option><option>Split Congress</option></select><small>Context only; never changes the math.</small></label>{controls.map(([label,value,set,min,max])=><div className="control" key={label}><label><span>{label}</span><b>{value}{label==="Forecast horizon"?" years":"%"}</b></label><input aria-label={label} type="range" min={min} max={max} step={label==="Forecast horizon"?1:.1} value={value} onChange={event=>set(Number(event.target.value))}/></div>)}<div className="notice">Deterministic identity: next debt = debt + outlays + interest − receipts. Starting debt is the latest Treasury observation; starting GDP is the latest BEA observation. CPI index {cpi.toFixed(1)} anchors 2026 dollars. Political labels add context only.</div></div></div>;
}
