import {administrations,history,nearestPrior} from "./data";
import {realValue} from "./real";
export type Party="Democratic"|"Republican";
export type CongressControl={congress:number;start:string;end:string;house:Party;senate:Party;houseSeats:string;senateSeats:string;speaker:string;senateLeader:string;note?:string};
const controls:[number,Party,Party,string,string,string,string][]=[
[89,"Democratic","Democratic","295–140","68–32","John McCormack","Mike Mansfield"],[90,"Democratic","Democratic","248–187","64–36","John McCormack","Mike Mansfield"],[91,"Democratic","Democratic","243–192","57–43","John McCormack","Mike Mansfield"],[92,"Democratic","Democratic","255–180","54–44","Carl Albert","Mike Mansfield"],[93,"Democratic","Democratic","242–192","56–42","Carl Albert","Mike Mansfield"],[94,"Democratic","Democratic","291–144","60–38","Carl Albert","Mike Mansfield"],[95,"Democratic","Democratic","292–143","61–38","Tip O’Neill","Robert Byrd"],[96,"Democratic","Democratic","277–158","58–41","Tip O’Neill","Robert Byrd"],[97,"Democratic","Republican","242–192","46–53","Tip O’Neill","Howard Baker"],[98,"Democratic","Republican","269–166","45–55","Tip O’Neill","Howard Baker"],[99,"Democratic","Republican","253–182","47–53","Tip O’Neill","Bob Dole"],[100,"Democratic","Democratic","258–177","55–45","Jim Wright","Robert Byrd"],[101,"Democratic","Democratic","260–175","55–45","Tom Foley","George Mitchell"],[102,"Democratic","Democratic","267–167","56–44","Tom Foley","George Mitchell"],[103,"Democratic","Democratic","258–176","57–43","Tom Foley","George Mitchell"],[104,"Republican","Republican","230–204","47–53","Newt Gingrich","Bob Dole"],[105,"Republican","Republican","226–207","45–55","Newt Gingrich","Trent Lott"],[106,"Republican","Republican","223–211","45–55","Dennis Hastert","Trent Lott"],[107,"Republican","Democratic","221–212","50–50","Dennis Hastert","Tom Daschle"],[108,"Republican","Republican","229–205","48–51","Dennis Hastert","Bill Frist"],[109,"Republican","Republican","232–202","44–55","Dennis Hastert","Bill Frist"],[110,"Democratic","Democratic","233–202","51–49","Nancy Pelosi","Harry Reid"],[111,"Democratic","Democratic","257–178","57–41","Nancy Pelosi","Harry Reid"],[112,"Republican","Democratic","242–193","51–47","John Boehner","Harry Reid"],[113,"Republican","Democratic","234–201","53–45","John Boehner","Harry Reid"],[114,"Republican","Republican","247–188","44–54","John Boehner / Paul Ryan","Mitch McConnell"],[115,"Republican","Republican","241–194","47–51","Paul Ryan","Mitch McConnell"],[116,"Democratic","Republican","235–199","45–53","Nancy Pelosi","Mitch McConnell"],[117,"Democratic","Democratic","222–213","50–50","Nancy Pelosi","Chuck Schumer"],[118,"Republican","Democratic","222–213","49–51","Kevin McCarthy / Mike Johnson","Chuck Schumer"],[119,"Republican","Republican","220–215","47–53","Mike Johnson","John Thune"]];
export const congresses:CongressControl[]=controls.map(([congress,house,senate,houseSeats,senateSeats,speaker,senateLeader])=>({congress,house,senate,houseSeats,senateSeats,speaker,senateLeader,start:`${1787+congress*2}-01-03`,end:congress===119?new Date().toISOString().slice(0,10):`${1789+congress*2}-01-03`,...(congress===107?{note:"Senate control changed during the term after Senator Jeffords changed affiliation; shown as transitional Democratic control for most of the Congress."}:{})}));
export function presidentAt(date:string){return administrations.find(a=>a.start<=date&&a.end>date)??administrations.at(-1)!}
export function classification(p:Party,h:Party,s:Party){if(h!==s)return "Split Congress";if(p===h)return `${p} unified government`;return `${p} president with divided government`}
export function controlPeriods(){const debt=history();return congresses.flatMap(c=>administrations.map(a=>({c,a,start:[c.start,a.start].sort().at(-1)!,end:[c.end,a.end].sort()[0]})).filter(x=>x.start<x.end).map(({c,a,start,end})=>{const first=nearestPrior(debt,start),last=nearestPrior(debt,end),days=Math.max(1,(Date.parse(end)-Date.parse(start))/86400000),increase=last.debt-first.debt;return {congress:c.congress,start,end,president:a.president,presidentParty:a.party,house:c.house,senate:c.senate,houseSeats:c.houseSeats,senateSeats:c.senateSeats,speaker:c.speaker,senateLeader:c.senateLeader,classification:classification(a.party,c.house,c.senate),startDebt:first.debt,endDebt:last.debt,increase,realIncrease:realValue(last.debt,last.date)-realValue(first.debt,first.date),annualized:increase/(days/365.2425),days,observations:debt.filter(d=>d.date>=start&&d.date<end).length,note:c.note}}))}
export function fiscalYearOwner(year:number){const date=`${year-1}-10-01`;return {fiscalYear:year,president:presidentAt(date).president,congress:congresses.find(c=>c.start<=date&&c.end>date)?.congress,rule:"Control at fiscal-year start; not causal budget attribution"}}

