import Link from "next/link";
import AdministrationChart from "@/components/AdministrationChart";
import LineChart from "@/components/LineChart";
import Snapshot from "@/components/Snapshot";
import { history, latest, summarize } from "@/lib/data";
import { validatedForecast } from "@/lib/forecasting";
import { money } from "@/lib/format";
import { controlPeriods } from "@/lib/government";
import { adjustSeries } from "@/lib/real";

export default function DashboardPage() {
  const observations=history(),current=latest(),recent=observations.slice(-120),real=adjustSeries(recent),forecast=validatedForecast(observations),administrations=summarize().slice(-6).reverse(),control=controlPeriods().at(-1)!;
  const fiveYear=recent.findLast(point=>point.date<=`${Number(current.date.slice(0,4))-5}-${current.date.slice(5)}`)??recent[0];
  const fiveYearChange=(current.total/fiveYear.debt-1)*100;
  const tenYear=forecast.forecast[10];
  const index=[["History","Select exact dates, change resolution, and inspect real-dollar movement.","/history"],["Government Control","See the president, House, and Senate serving at each observation.","/government-control"],["Forecast Center","Review model selection, errors, and widening uncertainty.","/forecast"],["Scenario Lab","Change transparent fiscal assumptions without partisan multipliers.","/scenario"],["Methodology","Trace source definitions, transformations, and limitations.","/methodology"]];
  return <main className="wrap dashboardPage"><header className="pageHead dashboardHead"><div><div className="eyebrow">Executive dashboard</div><h1>The U.S. debt picture, in one place.</h1><p>Current position, historical pace, institutional context, administration comparisons, and forecast uncertainty—each linked to deeper evidence.</p></div><div className="dashboardFreshness"><span>Official observation</span><b>{current.date}</b><small>U.S. Treasury Fiscal Data</small></div></header><Snapshot/><section className="dashboardGrid"><div className="panel dashboardPrimary"><div className="panelHeader chartNarrative"><div><h2>Debt trajectory and selected-window performance</h2><p>Use presets or exact dates. Every selection recomputes nominal, real, annualized, and daily change.</p></div><Link className="textLink" href="/history">Full history →</Link></div><LineChart intervalControls values={recent.map(point=>point.debt)} realValues={real.map(point=>point.debt)} labels={recent.map(point=>point.date.slice(0,7))} dates={recent.map(point=>point.date)} xLabel="Quarter-end observation" yLabel="Total public debt · nominal USD"/></div><aside className="dashboardRail"><div className="panel signalCard"><span className="eyebrow">Five-year movement</span><strong>+{fiveYearChange.toFixed(1)}%</strong><p>{money(fiveYear.debt)} to {money(current.total)}</p><Link href="/history">Inspect the window →</Link></div><div className="panel signalCard violet"><span className="eyebrow">10-year model range</span><strong>{money(tenYear.low)}–{money(tenYear.high)}</strong><p>Empirical 90% interval; not a point prediction.</p><Link href="/forecast">Inspect the forecast →</Link></div><div className="panel signalCard mint"><span className="eyebrow">Current institutional context</span><strong>{control.classification}</strong><p>{control.president} · {control.congress}th Congress · House {control.house[0]} / Senate {control.senate[0]}</p><Link href="/government-control">Open control timeline →</Link></div></aside></section><section className="dashboardLower"><div className="panel"><div className="panelHeader chartNarrative"><div><h2>Administration-period comparison</h2><p>Percentage change during each period, with timing shown as context rather than causation.</p></div><Link className="textLink" href="/administrations">All administrations →</Link></div><AdministrationChart rows={administrations}/></div><div className="panel dashboardIndex"><h2>Explore the evidence</h2>{index.map(([title,description,href])=><Link href={href} key={href}><b>{title}</b><span>{description}</span><i>→</i></Link>)}</div></section><div className="notice integrity"><b>Interpretation guardrail:</b> Debt changes reflect enacted laws, inherited obligations, economic conditions, emergencies, interest costs, and decisions across both elected branches. Timing alone does not establish causation.</div></main>;
}
